# Generated by Django 6.1 on 2026-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_journalentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('SALE', 'Sale'), ('CREDIT_SALE', 'Credit sale'), ('COLLECTION', 'Collection'), ('RM_PURCHASE', 'Raw material purchase'), ('BATCH', 'Production batch'), ('EXPENSE', 'Expense'), ('DISBURSEMENT', 'Disbursement'), ('PAYABLE_PAYMENT', 'Payable payment'), ('ORDER_DEPOSIT', 'Order deposit'), ('REMITTANCE', 'Rep remittance'), ('SWAP', 'Swap'), ('REVERSAL', 'Reversal'), ('CAPITAL', 'Owner capital'), ('OUTLET_TRANSFER_OUT', 'Outlet transfer (sent)'), ('OUTLET_TRANSFER_IN', 'Outlet transfer (received)')], max_length=20),
        ),
    ]
