# Generated by Django 6.1 on 2026-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_journalentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('SALE', 'Sale'), ('CREDIT_SALE', 'Credit sale'), ('COLLECTION', 'Collection'), ('RM_PURCHASE', 'Raw material purchase'), ('BATCH', 'Production batch'), ('EXPENSE', 'Expense'), ('DISBURSEMENT', 'Disbursement'), ('PAYABLE_PAYMENT', 'Payable payment'), ('ORDER_DEPOSIT', 'Order deposit'), ('REMITTANCE', 'Rep remittance'), ('SWAP', 'Swap'), ('REVERSAL', 'Reversal'), ('CAPITAL', 'Owner capital'), ('OUTLET_TRANSFER_OUT', 'Outlet transfer (sent)'), ('OUTLET_TRANSFER_IN', 'Outlet transfer (received)'), ('COGS_CORRECTION', 'Cost of goods sold — correction'), ('INVOICE_AR', 'Invoice raised to client'), ('INVOICE_AR_PAYMENT', 'Invoice payment received'), ('INVOICE_AP', 'Supplier bill recorded'), ('INVOICE_AP_PAYMENT', 'Supplier bill paid'), ('MANUAL', 'Manual journal entry'), ('BATCH_LOSS', 'Production loss')], max_length=20),
        ),
    ]
