# Generated by Django 6.1 on 2026-09-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0002_remove_business_token_balance_subscriptionextension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
