# Generated by Django 6.1 on 2026-09-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('platformadmin', '0001_initial'),
        ('production', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='receiver_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.inventorylocation'),
        ),
        migrations.AddField(
            model_name='distributionline',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.distribution'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='production.category'),
        ),
        migrations.AddField(
            model_name='distributionline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product'),
        ),
        migrations.AddField(
            model_name='productformula',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productformula',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='production.product'),
        ),
        migrations.AddField(
            model_name='formulaline',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.productformula'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.productformula'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='qareport',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qareport',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qa', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business'),
        ),
        migrations.AddField(
            model_name='formulaline',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.rawmaterial'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rawmaterialpurchase',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='production.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rawmaterialpurchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.supplier'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.rawmaterialpurchase'),
        ),
        migrations.AlterUniqueTogether(
            name='productformula',
            unique_together={('product', 'version')},
        ),
    ]
