# Generated by Django 6.1 on 2026-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_product_active_product_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shelf_life_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
