# Generated by Django 6.1 on 2026-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_product_shelf_life_days_productionbatch_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_price',
        ),
        migrations.AddField(
            model_name='product',
            name='custom_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='custom_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
