# Generated by Django 6.1 on 2026-09-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_distribution_confirmed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_of_measure',
            field=models.CharField(max_length=20),
        ),
    ]
