# Generated by Django 6.1 on 2026-09-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_rawmaterial_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='productformula',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
