# Generated by Django 6.1 on 2026-09-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productformula_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribution_lines', to='production.productionbatch'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
