# Generated by Django 6.1 on 2026-09-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_distributionline_batch_and_more'),
        ('sales', '0007_stockrequest_fulfillment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='stock_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='sales.stockrequest'),
        ),
    ]
