# Generated by Django 6.1 on 2026-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_distribution_stock_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
