# Generated by Django 6.1 on 2026-09-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_distribution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
