# Generated by Django 6.1 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_rawmaterialpurchase_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialpurchase',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
