# Generated by Django 6.1 on 2026-09-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0014_rawmaterialpurchase_is_reversed'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='sender_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions_sent', to='core.branch'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_batches', to='core.branch'),
        ),
        migrations.AddField(
            model_name='rawmaterialpurchase',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_material_purchases', to='core.branch'),
        ),
    ]
