# Generated by Django 6.1 on 2026-09-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_backfill_branch_and_require'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensation',
            name='is_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='loss_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
