# Generated by Django 6.1 on 2026-09-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('platformadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text="Which of the business's subscribed modules this user can open.", related_name='users_with_access', to='platformadmin.module'),
        ),
    ]
