# Generated by Django 6.1 on 2026-09-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_tiers',
            field=models.JSONField(blank=True, default=list, help_text='Which product price tiers (RETAIL/WHOLESALE/DISTRIBUTION/CUSTOM) this seller may use at the POS.'),
        ),
    ]
