# Generated by Django 6.1 on 2026-09-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('platformadmin', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=80)),
                ('account_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebtorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('method', models.CharField(max_length=15)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.debtor')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PRODUCTION_STORE', 'Finished goods store'), ('OUTLET', 'Outlet'), ('REP', 'Sales rep')], max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='core.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('rep', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.inventorylocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='debtor',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.inventorylocation'),
        ),
        migrations.CreateModel(
            name='MomoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('number', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('SWAP', 'Swap'), ('REFUND', 'Refund'), ('STOCK_REQUEST', 'Stock request')], max_length=15)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=40)),
                ('acted_as', models.CharField(blank=True, max_length=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('CREDIT', 'Credit')], max_length=15)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('debtor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.debtor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.inventorylocation')),
                ('paid_into_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.bankaccount')),
                ('paid_into_momo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.momoaccount')),
                ('served_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('reason', models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('SALE', 'Sale'), ('SWAP_IN', 'Swap in'), ('SWAP_OUT', 'Swap out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='sales.inventorylocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='DRAFT', max_length=10)),
                ('lines', models.JSONField(default=list)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('requester_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.inventorylocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WholesaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BILLED', 'Billed'), ('COMPLETED', 'Completed')], default='OPEN', max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.inventorylocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.inventorylocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product')),
            ],
            options={
                'unique_together': {('location', 'product')},
            },
        ),
    ]
