# Generated by Django 6.1 on 2026-09-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0002_remove_business_token_balance_subscriptionextension_and_more'),
        ('sales', '0002_sale_customer_name_sale_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='sales.inventorylocation')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('location', 'date')},
            },
        ),
    ]
