# Generated by Django 6.1 on 2026-09-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0003_business_tagline'),
        ('production', '0008_productformula_is_active'),
        ('sales', '0004_stockmovement_counterparty_stockmovement_moved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('CREDIT', 'Credit'), ('OUTLET_TRANSFER', 'Outlet Transfer')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('DISTRIBUTION', 'Distribution'), ('SALE', 'Sale'), ('SWAP_IN', 'Swap in'), ('SWAP_OUT', 'Swap out'), ('ADJUSTMENT', 'Adjustment'), ('RETURN', 'Return'), ('TRANSFER_OUT', 'Outlet transfer out'), ('TRANSFER_IN', 'Outlet transfer in')], max_length=15),
        ),
        migrations.CreateModel(
            name='OutletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('DISPUTED', 'Disputed')], default='SENT', max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_transfers_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_transfer', to='sales.expense')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='sales.inventorylocation')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlet_transfer', to='sales.sale')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='sales.inventorylocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.outlettransfer')),
            ],
        ),
    ]
