# Generated by Django 6.1 on 2026-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_payment_method_alter_stockmovement_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='counterparty_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
