# Generated by Django 6.1 on 2026-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_stockmovement_counterparty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrequest',
            name='fulfillment_mode',
            field=models.CharField(choices=[('WAIT', "Send what's available now, keep the rest on order"), ('AVAILABLE_ONLY', "Send what's available now only, cancel the rest")], default='WAIT', max_length=15),
        ),
        migrations.AlterField(
            model_name='stockrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIAL', 'Partially sent — remainder on order'), ('FULFILLED', 'Fulfilled')], default='DRAFT', max_length=10),
        ),
    ]
