# Generated by Django 6.1 on 2026-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_stockrequest_fulfillment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorpayment',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
