# Generated by Django 6.1 on 2026-09-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_backfill_debtorpayment_balance_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorpayment',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DebtorPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.debtorpayment')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debtor_payment_allocations', to='sales.sale')),
            ],
        ),
    ]
