# Generated by Django 6.1 on 2026-09-09 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_debtorpayment_is_reversed_debtorpaymentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_from_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.bankaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_from_momo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.momoaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank')], default='CASH', max_length=15),
        ),
    ]
