# Generated by Django 6.1 on 2026-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_expense_paid_from_bank_expense_paid_from_momo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtorpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='expense',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='stockrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
