# Generated by Django 6.1 on 2026-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_debtorpayment_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('SWAP', 'Swap'), ('REFUND', 'Refund'), ('STOCK_REQUEST', 'Stock request'), ('SALE_REVERSAL', 'Sale reversal')], max_length=15),
        ),
    ]
