# Generated by Django 6.1 on 2026-09-19 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platformadmin', '0003_business_tagline'),
        ('production', '0017_dispensation_is_loss_dispensation_note_and_more'),
        ('sales', '0013_sale_is_reversed_alter_pendingaction_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RECEIVED', 'Received'), ('DISPUTED', 'Disputed')], default='SENT', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('idempotency_key', models.CharField(blank=True, max_length=40)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platformadmin.business')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_returns_created', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_sent', to='sales.inventorylocation')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_received', to='sales.inventorylocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.product')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.stockreturn')),
            ],
        ),
    ]
