# Generated by Django 6.1 on 2026-09-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_stockreturn_stockreturnline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='action_type',
            field=models.CharField(choices=[('SWAP', 'Swap'), ('REFUND', 'Refund'), ('STOCK_REQUEST', 'Stock request'), ('SALE_REVERSAL', 'Sale reversal'), ('RETURN_TO_PRODUCTION', 'Return to Production')], max_length=21),
        ),
    ]
